name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # Atualiza a cada hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, activity, community, repositories"
          repositories_affiliations: "owner, collaborator, organization_member"
          plugin_lines: yes
          plugin_traffic: yes
